apiVersion: v1
kind: Service
metadata:
  name: microservice-app2-service
  labels:
    app: microservice-app2
spec:
  selector:
    app: microservice-app2
    tier: web
  ports:
    - port: 80
      targetPort: 6060
  type: LoadBalancer
